nodes:
  eth:
    full:
      url: "xxx"
      concurrent_clients_number: 3
    archive:
      url: "xxx"
      concurrent_clients_number: 3
  generator:
    start_block_number: 28978000
    end_block_number: 28978170
bscscan:
  api:
    url: "https://api.bscscan.com/api"
    key: "xxx"
bitquery:
  api:
    url: "https://graphql.bitquery.io/"
    key: "xxx"
database:
  redis:
    addr: ":6379"
    password: ""
    db: 0
  badger:
    path: "/home/unpack/db"
  clickhouse:
    host: "xxx"
    database: "unpack"
    username: "xxx"
    password: "xxx"

syncers:
  fourbyte:
    url: "https://www.4byte.directory/api/v1/signatures/"
    write_to_clickhouse: true
    chain_id: 1

  bscscan:
    verified_contracts_path: "/home/unpack/bscscan"
    write_to_clickhouse: true

  sourcify:
    url: "xxx"
    max_retries: 3
    retry_dely: 2
    rate_limit_s: 20
    write_to_clickhouse: true
    chain_ids: [1, 56]